import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const app = readFileSync(new URL("../src/App.vue", import.meta.url), "utf8")
const component = readFileSync(new URL("../src/TaskStatusIndicator.vue", import.meta.url), "utf8")
const css = readFileSync(new URL("../src/style.css", import.meta.url), "utf8")

assert.doesNotMatch(app, /认领负责人/, "user-facing claim actions use task language")
assert.match(app, /认领任务/)
assert.match(app, /认领中…/)
assert.doesNotMatch(app, /status-actions|statusOptions|v-for="value in \(\['todo', 'doing', 'done'\]/)

assert.match(component, /status: TaskStatus/)
assert.match(component, /class="task-status-icon"[\s\S]*?<circle/)
assert.match(component, /status-progress-half/)
assert.match(component, /status-check/)
assert.match(component, /aria-haspopup="menu"/)
assert.match(component, /:aria-expanded="menuOpen"/)
assert.match(component, /role="menu"/)
assert.match(component, /role="menuitemradio"/)
assert.match(component, /:aria-checked="status === option"/)
assert.match(component, /event\.key === "Escape"/)
assert.match(component, /event\.key === "ArrowDown" \|\| event\.key === "ArrowUp"/)
assert.match(component, /event\.key === "Tab"[\s\S]*?closeMenu\(\)/)
assert.match(component, /menuBounds\.right > window\.innerWidth - 8/)
assert.match(component, /document\.addEventListener\("pointerdown"/)
assert.match(component, /closeMenu\(true\)/)
assert.match(component, /emit\("update-status", status\)/)
assert.match(component, /v-if="blocked" class="task-status-blocked"/)

const rootListStart = app.indexOf('<article v-for="task in rootTasks"')
const rootCards = app.slice(rootListStart, app.indexOf('<div v-else class="empty empty-action empty-state">', rootListStart))
assert.match(rootCards, /:editable="isManager && taskView === 'all' && childTasks\(task\.id\)\.length === 0"/)
assert.match(rootCards, /@update-status="updateOwnTaskStatus\(task, \$event\)"/)
assert.match(rootCards, /<TaskStatusIndicator :status="child\.status"[\s\S]*?:editable="isManager"/)
assert.match(rootCards, /class="child-task-heading"[\s\S]*?class="child-task-owner"[\s\S]*?class="task-title-link(?: [^"]*)?"/)
assert.match(app, /:editable="isManager && detailChildren\.length === 0"/)
assert.match(app, /:editable="isManager"[\s\S]*?@update-status="updateOwnTaskStatus\(detailTask, \$event\)"/)
assert.match(app, /async function updateOwnTaskStatus\(task: Task, status: TaskStatus\)[\s\S]*?runTaskAction\(task, `status:\$\{status\}`,[\s\S]*?api\.updateTask\(task\.id, \{ status \}\)/)

assert.match(css, /\.task-status-indicator\s*\{[^}]*color:\s*var\(--muted\)/s)
assert.match(css, /\.task-status-indicator\.status-doing \.task-status-icon\s*\{[^}]*color:\s*var\(--accent\)/s)
assert.match(css, /\.task-status-indicator\.status-done \.task-status-icon\s*\{[^}]*color:\s*var\(--success\)/s)
assert.match(css, /\.task-status-indicator\.status-done \.task-status-icon > circle,[\s\S]*?fill:\s*currentColor/s)
assert.match(css, /\.task-status-blocked\s*\{[^}]*color:\s*var\(--muted\)/s)
assert.match(css, /\.task-status-menu\s*\{[^}]*max-width:\s*calc\(100vw - 24px\)/s)
assert.match(css, /\.task-status-menu\.align-right\s*\{[^}]*right:\s*0[^}]*left:\s*auto/s)
assert.match(css, /@media \(max-width: 560px\)[\s\S]*?\.task-status-menu\s*\{[^}]*max-width:\s*calc\(100vw - 28px\)/s)
assert.match(css, /\.task-actions \.primary\.small-action\s*\{[^}]*min-height:\s*34px[^}]*font-size:\s*13px/s)

console.log("Compact task status, role-gated menu, accessibility, blocked hint, and claim copy passed")
